species: arabidopsis

seq_info:
  type: RNA-Seq
  stranded: yes
  mode: PE
  replicate: 3
  #replicate: 3+4+3+3 (if the number of replicates are different for each sample)

path: /cluster/home/xfu/Project/ZHM_20180801/RNA-Seq/fastq/

samples:
  - ABA1
  - ABA2
  - ABA3
  - ABAP1
  - ABAP2
  - ABAP3
  - mock1
  - mock2
  - mock3
  - MV1
  - MV2
  - MV3

groups:
  - ABA
  - ABA
  - ABA
  - ABAP
  - ABAP
  - ABAP
  - mock
  - mock
  - mock
  - MV
  - MV
  - MV

design_table: design_table.tsv
#design_table: none

venn_table: venn_table.tsv

cpu: 30

strandness_hisat2: RF ## R (SE); RF (PE)

strandness_htseq: reverse

Rscript_path: /cluster/home/xfu/R/3.5.1/bin/Rscript

conda_path: /cluster/home/xfu/miniconda2/envs/gmatic/bin

adapter: /cluster/home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

fold_change: 
  - 1.5
  - 2

# Arabidopsis
index: /cluster/home/xfu/Gmatic7/genome/tair10/hisat2/tair10
 
gtf: /cluster/home/xfu/Gmatic7/gene/tair10/tair10.gtf
 
bed: /cluster/home/xfu/Gmatic7/gene/tair10/tair10_gene.bed
 
gene_anno: /cluster/home/xfu/Gmatic7/gene/tair10/tair10_gene_anno.tsv
 
gene_length: ./script/tair10_merged_exons_length.tsv
 
IGV: /cluster/home/xfu/igv/genomes/tair10.genome

# Nicotiana benthamiana
#index: /cluster/home/xfu/Gmatic7/genome/Niben/hisat2/Niben101
# 
#gtf: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101.gtf
# 
#bed: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_gene.bed
# 
#gene_anno: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_gene_anno_ath.tsv
# 
#gene_length: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_merged_exons_length.tsv
# 
#IGV: /cluster/home/xfu/igv/genomes/Niben101.genome

